# Generated by Django 2.2.3 on 2019-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190728_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportUserprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sport_userprofile',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
